development: 
  clients:
    default:
      database: auth_api_development
      hosts:
        - <%= ENV['MONGO_HOST'] ||= "localhost:27017" %>

test:
  clients:
    default:
      database: auth_api_test
      hosts:
        - <%= ENV['MONGO_HOST'] ||= "localhost:27017" %>
      options:
        read:
          mode: :primary
        max_pool_size: 1

production:
  clients:
    default:
      uri: <%= ENV['MONGO_URI'] %>
      options:
        connect_timeout: 15
